export default {
  FETCH_ITEMS: "FETCH_ITEMS",
  FETCH_ITEMS_SUCCESS: "FETCH_ITEMS_SUCCESS",
  FETCH_ITEMS_ERROR: "FETCH_ITEMS_ERROR",
  CLEAR_ITEMS: "CLEAR_ITEMS",

  FETCH_ITEM: "FETCH_ITEM",
  FETCH_ITEM_SUCCESS: "FETCH_ITEM_SUCCESS",
  FETCH_ITEM_ERROR: "FETCH_ITEM_ERROR",
  CLEAR_ITEM: "CLEAR_ITEMS"
};
